baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'South African Minority Union'
theme = 'lugo'

[params]
  favicon = "/favicon.png"
  stylesheet = "/style.css"
  indexarticles = 50
  taglist = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true